# 1 Numpy数组对象

In [1]:
import numpy as np

In [2]:
# 用arange函数创建数组，并获取其数据类型
a = np.arange(5)

In [3]:
a.dtype

dtype('int32')

In [4]:
# 查看a中元素和维度
a

array([0, 1, 2, 3, 4])

In [5]:
a.shape

(5,)

# 2 创建多维数组

（1）创建一个多维数组

（2）显示该数组的维度

In [8]:
m = np.array([np.arange(2), np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [9]:
m.shape

(2, 2)

<center>突击检测：ndarray对象维度属性的存储方式</center>

问题1：ndarray对象的维度属性是以下哪种方式存储的？

（1）逗号隔开的字符串<br>
（2）Python列表（list）<br>
（3）Python元组（tuple）<br>

<br><br><br>
答案：（3）

In [10]:
# 选取数组元素
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [11]:
a[0, 0]

1

In [13]:
# 数据类型
np.float64(42)

42.0

In [14]:
np.int8(42.0)

42

In [15]:
bool(42)

True

In [16]:
float(True)

1.0

In [17]:
float(False)

0.0

In [23]:
np.arange(7, dtype=int)

array([0, 1, 2, 3, 4, 5, 6])

In [24]:
# 数据类型对象
a.dtype.itemsize

4

In [26]:
np.arange(7, dtype='f')

array([0., 1., 2., 3., 4., 5., 6.], dtype=float32)

In [27]:
np.arange(7, dtype='D')   # 复数

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [35]:
# 自定义数据类型
np.dtype(float)

dtype('float64')

In [36]:
np.dtype('d')

dtype('float64')

# 3 一维数组的索引和切片

In [39]:
a = np.arange(9)
a[3:7]

array([3, 4, 5, 6])

In [40]:
a[:7:2]     # 下标为0~6 以2为步长

array([0, 2, 4, 6])

In [41]:
a[::-1]   # 翻转数组

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

# 4 动手实践：多维数组的切片和索引

ndarry（）支持在多维数组上的切片操作，为了方便起见，可以使用一个省略号（...）来遍历剩下的维度

In [42]:
b = np.arange(24).reshape(2, 3, 4)

In [43]:
b.shape

(2, 3, 4)

In [44]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

多维数组b中有0~23的整数，共24个整数，是一个2*3*4的三维数组。可以形象地把它看做一个两层楼建筑，每层楼有12个房间，并排列成3行4列。

可以用三维坐标来选定任意一个房间，如楼层、行号和列号。例如，选定第一层楼、第1行、第一列的房间，可以这么表示：<br>
``
In: b[0,0,0]
Out: 0
``

In [45]:
# 如果不关心楼层，也就是说要选取所有楼层的第一行、第一列的房间，那么可以将第1个下表用英文标点的冒号：来替代

b[:,0,0]

array([ 0, 12])

In [46]:
b[0]  # 等价于b[0,:,:]   b[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
# 选取第一层楼、第2排的所有房间
b[0,1]

array([4, 5, 6, 7])

In [49]:
# 在上面的数组切片中 间隔地选定元素
b[0,1,::2]

array([4, 6])

In [50]:
# 如果要选取所有楼层的位于第2列的房间，即不指定楼层和行号，用如下代码即可：
b[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [51]:
# 类似的，可以选取所有位于第2行的房间，而不指定楼层和列号
b[:,1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [52]:
# 要选取第一层楼的最后一列的所有房间
b[0,:,-1]

array([ 3,  7, 11])

In [53]:
# 如果要反向选取第一层楼的最后一列的所有房间
b[0,::-1,-1]

array([11,  7,  3])

In [54]:
# 切片中间隔地选定元素
b[0,::2,-1]

array([ 3, 11])

In [55]:
# 将第一层楼和第二层楼的房间交换
b[::-1]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

# 5 动手实践：改变数组的维度

In [56]:
# 可以使用reval函数完成战平的操作
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [57]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [58]:
# flatten 这个函数与ravel函数的共嗯那个相同，不过flatten函数会请求分配内存来保存结果，而ravel函数知识返回数组的一个视图(view)
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [59]:
# 用元组设置维度，除了使用reshape函数，我们可以直接用一个正整数元组来设置数组的维度，如下所示
b.shape = (6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [60]:
# transpose在线性代数中，转置矩阵是很常见的操作。对于多维数组，可以这么做：
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [61]:
b.T   # 等价于上面的b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [62]:
# resize 和 reshape函数的功能一样，但resize会直接修改所操作的数组：
b.resize((2, 12))

In [63]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [65]:
b.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [66]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [67]:
b.resize(3,8)

In [68]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

**小结**<br>
- revel()、flatten()功能一样，都是展平数组
- resize()和reshape()功能一样，但resize会改变所操作的数组

# 6 数组的组合

Numpy数组有水平组合、垂直组合和深度组合等多种组合方式，我们将使用vstack、dstack、hstack、column_stack、row_stack以及concatenate函数来完成数组的组合

In [70]:
# 首先来创建一些数组
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
b = 2* a

In [72]:
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [75]:
# 水平组合
np.hstack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [76]:
# 等价于concatenate()函数 axis = 1的
np.concatenate((a, b), axis=1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [77]:
# 垂直组合
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [78]:
# 等价于concatenate函数的axis参数设置为0
np.concatenate((a, b), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [79]:
# 深度组合   将一系列数组沿着纵轴（深度）方向进行层叠组合
# 举个例子： 有若干张二维平面内的图像点阵数据，我们可以将这些图像数据沿着纵轴方向层叠在一起，这就形象地解释了什么是深度组合
np.dstack((a, b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [80]:
np.dstack((a, b)).shape

(3, 3, 2)

In [81]:
# 列组合      column_stack函数对于以为数组将按列方向进行组合
oned = np.arange(2)
twice_oned = 2 * oned

np.column_stack((oned, twice_oned))

array([[0, 0],
       [1, 2]])

In [82]:
np.column_stack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

对于二维数组，column_statck于hstack的效果是相同的

In [83]:
# 可以用 == 来比较二者是否等价
np.column_stack((a, b)) == np.hstack((a, b))

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [84]:
# 行组合 row_stack
np.row_stack((oned, twice_oned))

array([[0, 1],
       [0, 2]])

In [85]:
# 对于二维数组， row_stack与vstack的效果是相同的
np.row_stack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [86]:
np.row_stack((a, b)) == np.vstack((a, b))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

** 小结 **
- vstack()与concatenate(,axis=0) 等价，      表示垂直组合
- hstack()与concatenate(, axis=1)等价，     表示水平组合
- 对于二维数组而言，column_stack与 hstack等价-----列组合<br>
  row_stack与vstack等价------行组合
- concatenate函数在深度学习用的较多

# 7 数组的分割

Numpy数组可以进行水平、垂直或深度分割，相关的函数有 hsplit、vsplit、dsplit和split。我们可以将数组分割成相同大小的子数组，也可以指定原数组中需要分割的位置

(1) 水平分割

In [87]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
np.hsplit(a, 3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [89]:
# 对同样的数组，调用split函数并在参数中指定参数axis=1，等价于上面效果
np.split(a, 3, axis=1)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

（2）垂直分割 vsplit函数将把数组沿着垂直方向分割

In [90]:
np.vsplit(a, 3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [91]:
np.split(a, 3, axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

（3）深度分割        dsplit函数将按照深度方向分割数组，我们先创建一个三维数组

In [92]:
c = np.arange(27).reshape(3, 3, 3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [93]:
np.dsplit(c, 3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

# 8 数组的属性

除了shape和dtype属性以外，ndarray对象还有很多其他的属性

In [100]:
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [101]:
b.ndim   # 数组b的维度

2

In [99]:
b.size  # 数组b的元素总个数

9

In [102]:
b.itemsize   # 数组中的元素在内存中所占的字节数

4

In [103]:
b.nbytes       # 整个数组所占存储空间   相当于 b.itemsize * b.ndim

36

In [104]:
# 在numpy中，复数的虚部是用j来表示的，例如，我们可以创建一个由负数构成的数组
b= np.array([1.j+1, 2.j+3])
b

array([1.+1.j, 3.+2.j])

In [105]:
# real属性，给出负数数组的实部。如果数组中只包含实数元素，则其real属性将输出原数组
b.real

array([1., 3.])

In [106]:
# imag属性给出负数数组的虚部
b.imag

array([1., 2.])

In [107]:
# 如果数组中包含复数元素，则其数据类型自动变为复数型
b.dtype

dtype('complex128')

In [108]:
b.dtype.str  # 大端序是将最高位字节存储在最低的内存地址处，用>表示；与之相反，小端序是将最低为字节存储在最低的内存地址处，用<表示

'<c16'

# 9 动手实践：数组的转换

使用toList函数将Numpy数组转换成Python列表

In [109]:
b

array([1.+1.j, 3.+2.j])

In [110]:
b.tolist()

[(1+1j), (3+2j)]

astype函数可以在转换数组时指定数据类型

In [111]:
b.astype(int)

D:\software\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  """Entry point for launching an IPython kernel.


array([1, 3])

In [113]:
# 出现警告是因为在转换的时候丢失了复数的虚部。astype函数可以接受苏话剧类型为字符串的参数
b.astype('complex')   # 这次使用了正确的数据类型，因此不会在显示任何警告信息

array([1.+1.j, 3.+2.j])

## 总结

本章主要介绍了numpy的基础知识，涉及改变数据维度的操作有很多种----组合、调整、设置维度和分割等。在这一章中，对很多改变数组维度的实用函数进行了说明。

在学完基础知识后，将进入第三章学习Numpy中的常用函数，包括基本数学函数和统计函数等